<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://nav.no/emottak/services/archiver" 
	xmlns:arch="http://nav.no/emottak/archiver" 
	targetNamespace="http://nav.no/emottak/services/archiver">
	<wsdl:types>
		<xs:schema targetNamespace="http://nav.no/emottak/services/archiver" elementFormDefault="qualified">
			<xs:import namespace="http://nav.no/emottak/archiver" schemaLocation="archiver.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="ArchiveReq">
		<wsdl:part name="parameters" element="arch:LogAndArchiveRequest"/>
	</wsdl:message>
	<wsdl:message name="ArchiveResp">
		<wsdl:part name="parameters" element="arch:LogAndArchiveResponse"/>
	</wsdl:message>
	<wsdl:portType name="ArchiverPortType">
		<wsdl:operation name="archive">
			<wsdl:input message="tns:ArchiveReq"/>
			<wsdl:output message="tns:ArchiveResp"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ArchiverBinding" type="tns:ArchiverPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="archive">
			<soap:operation soapAction="urn:archive"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ArchiverService">
		<wsdl:port name="Archiver" binding="tns:ArchiverBinding">
			<soap:address location="https://localhost:9443/nav-emottak-archiver-web/services/archiver"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
