<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/Binding" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/Binding" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="behandleInngaaendeJournal.wsdl" namespace="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1"/>
  <wsdl:binding name="BehandleInngaaendeJournal_v1Binding" type="wsdl_1:BehandleInngaaendeJournal_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/Bindingping/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ferdigstillJournalfoering">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/BindingferdigstillJournalfoering/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ferdigstillJournalfoeringFault">
        <soap:fault name="ferdigstillJournalfoeringFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ferdigstillJournalfoeringFault1">
        <soap:fault name="ferdigstillJournalfoeringFault1" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ferdigstillJournalfoeringFault2">
        <soap:fault name="ferdigstillJournalfoeringFault2" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ferdigstillJournalfoeringFault3">
        <soap:fault name="ferdigstillJournalfoeringFault3" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ferdigstillJournalfoeringFault4">
        <soap:fault name="ferdigstillJournalfoeringFault4" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="oppdaterJournalpost">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/BindingoppdaterJournalpost/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="oppdaterJournalpostFault">
        <soap:fault name="oppdaterJournalpostFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="oppdaterJournalpostFault1">
        <soap:fault name="oppdaterJournalpostFault1" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="oppdaterJournalpostFault2">
        <soap:fault name="oppdaterJournalpostFault2" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="oppdaterJournalpostFault3">
        <soap:fault name="oppdaterJournalpostFault3" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="oppdaterJournalpostFault4">
        <soap:fault name="oppdaterJournalpostFault4" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BehandleInngaaendeJournal_v1">
    <wsdl:port binding="tns:BehandleInngaaendeJournal_v1Binding" name="BehandleInngaaendeJournal_v1Port">
      <soap:address location="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/BindingBehandleInngaaendeJournal_v1/BehandleInngaaendeJournal_v1Port"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>