<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1" location="behandleInngaaendeJournal.wsdl">
    </wsdl:import>
  <wsdl:binding name="BehandleInngaaendeJournal_v1Binding" type="wsdl_1:BehandleInngaaendeJournal_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/BehandleInngaaendeJournal_v1/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ferdigstillJournalfoering">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/BehandleInngaaendeJournal_v1/ferdigstillJournalfoeringRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="objektIkkeFunnet">
        <soap:fault name="objektIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ferdigstillingIkkeMulig">
        <soap:fault name="ferdigstillingIkkeMulig" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="journalpostIkkeInngaaende">
        <soap:fault name="journalpostIkkeInngaaende" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="oppdaterJournalpost">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleInngaaendeJournal/v1/BehandleInngaaendeJournal_v1/oppdaterJournalpostRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="oppdateringIkkeMulig">
        <soap:fault name="oppdateringIkkeMulig" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="objektIkkeFunnet">
        <soap:fault name="objektIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="journalpostIkkeInngaaende">
        <soap:fault name="journalpostIkkeInngaaende" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BehandleInngaaendeJournal_v1">
    <wsdl:port name="BehandleInngaaendeJournal_v1Port" binding="tns:BehandleInngaaendeJournal_v1Binding">
      <soap:address location="http://localhost:9080/virksomhet/behandleInngaaendeJournal_v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
