//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 08:35:22 AM CET 
//


package no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.joda.time.DateTime;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="behandlingsId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="behandlingskjedeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aktor" type="{http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1}aktor" minOccurs="0"/>
 *         &lt;element name="tema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="behandlingsType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="opprettetDato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="avsluttetDato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="anvendteFakta" type="{http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1}faktumListe" minOccurs="0"/>
 *         &lt;element name="produserteFakta" type="{http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1}faktumListe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "behandlingsId",
    "behandlingskjedeId",
    "aktor",
    "tema",
    "behandlingsType",
    "opprettetDato",
    "avsluttetDato",
    "anvendteFakta",
    "produserteFakta"
})
@XmlRootElement(name = "behandlingsinformasjon")
public class Behandlingsinformasjon {

    protected String behandlingsId;
    protected String behandlingskjedeId;
    protected XMLAktor aktor;
    protected String tema;
    protected String behandlingsType;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime opprettetDato;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime avsluttetDato;
    protected XMLFaktumListe anvendteFakta;
    protected XMLFaktumListe produserteFakta;

    /**
     * Gets the value of the behandlingsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehandlingsId() {
        return behandlingsId;
    }

    /**
     * Sets the value of the behandlingsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehandlingsId(String value) {
        this.behandlingsId = value;
    }

    /**
     * Gets the value of the behandlingskjedeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehandlingskjedeId() {
        return behandlingskjedeId;
    }

    /**
     * Sets the value of the behandlingskjedeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehandlingskjedeId(String value) {
        this.behandlingskjedeId = value;
    }

    /**
     * Gets the value of the aktor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAktor }
     *     
     */
    public XMLAktor getAktor() {
        return aktor;
    }

    /**
     * Sets the value of the aktor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAktor }
     *     
     */
    public void setAktor(XMLAktor value) {
        this.aktor = value;
    }

    /**
     * Gets the value of the tema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTema() {
        return tema;
    }

    /**
     * Sets the value of the tema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTema(String value) {
        this.tema = value;
    }

    /**
     * Gets the value of the behandlingsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehandlingsType() {
        return behandlingsType;
    }

    /**
     * Sets the value of the behandlingsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehandlingsType(String value) {
        this.behandlingsType = value;
    }

    /**
     * Gets the value of the opprettetDato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getOpprettetDato() {
        return opprettetDato;
    }

    /**
     * Sets the value of the opprettetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpprettetDato(DateTime value) {
        this.opprettetDato = value;
    }

    /**
     * Gets the value of the avsluttetDato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getAvsluttetDato() {
        return avsluttetDato;
    }

    /**
     * Sets the value of the avsluttetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsluttetDato(DateTime value) {
        this.avsluttetDato = value;
    }

    /**
     * Gets the value of the anvendteFakta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLFaktumListe }
     *     
     */
    public XMLFaktumListe getAnvendteFakta() {
        return anvendteFakta;
    }

    /**
     * Sets the value of the anvendteFakta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFaktumListe }
     *     
     */
    public void setAnvendteFakta(XMLFaktumListe value) {
        this.anvendteFakta = value;
    }

    /**
     * Gets the value of the produserteFakta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLFaktumListe }
     *     
     */
    public XMLFaktumListe getProduserteFakta() {
        return produserteFakta;
    }

    /**
     * Sets the value of the produserteFakta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFaktumListe }
     *     
     */
    public void setProduserteFakta(XMLFaktumListe value) {
        this.produserteFakta = value;
    }

}
