//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 08:35:43 AM CET 
//


package no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLBehandlingsinformasjon }
     * 
     */
    public XMLBehandlingsinformasjon createXMLBehandlingsinformasjon() {
        return new XMLBehandlingsinformasjon();
    }

    /**
     * Create an instance of {@link XMLAktor }
     * 
     */
    public XMLAktor createXMLAktor() {
        return new XMLAktor();
    }

    /**
     * Create an instance of {@link XMLFaktumListe }
     * 
     */
    public XMLFaktumListe createXMLFaktumListe() {
        return new XMLFaktumListe();
    }

    /**
     * Create an instance of {@link XMLStartBehandling }
     * 
     */
    public XMLStartBehandling createXMLStartBehandling() {
        return new XMLStartBehandling();
    }

    /**
     * Create an instance of {@link XMLMelding }
     * 
     */
    public XMLMelding createXMLMelding() {
        return new XMLMelding();
    }

    /**
     * Create an instance of {@link XMLFaktum }
     * 
     */
    public XMLFaktum createXMLFaktum() {
        return new XMLFaktum();
    }

}
