//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 08:35:43 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1")
package no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1;
