//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 08:35:43 AM CET 
//


package no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aktor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aktor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aktorId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="navIdent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ansvarligEnhet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aktor", propOrder = {
    "aktorId",
    "navIdent",
    "ansvarligEnhet"
})
public class XMLAktor {

    protected String aktorId;
    protected String navIdent;
    protected String ansvarligEnhet;

    /**
     * Gets the value of the aktorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAktorId() {
        return aktorId;
    }

    /**
     * Sets the value of the aktorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAktorId(String value) {
        this.aktorId = value;
    }

    /**
     * Gets the value of the navIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavIdent() {
        return navIdent;
    }

    /**
     * Sets the value of the navIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavIdent(String value) {
        this.navIdent = value;
    }

    /**
     * Gets the value of the ansvarligEnhet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsvarligEnhet() {
        return ansvarligEnhet;
    }

    /**
     * Sets the value of the ansvarligEnhet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsvarligEnhet(String value) {
        this.ansvarligEnhet = value;
    }

}
