//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 08:35:43 AM CET 
//


package no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faktumListe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faktumListe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faktum" type="{http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1}faktum" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faktumListe", propOrder = {
    "faktum"
})
public class XMLFaktumListe {

    protected List<XMLFaktum> faktum;

    /**
     * Gets the value of the faktum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faktum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaktum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLFaktum }
     * 
     * 
     */
    public List<XMLFaktum> getFaktum() {
        if (faktum == null) {
            faktum = new ArrayList<XMLFaktum>();
        }
        return this.faktum;
    }

}
