//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 08:35:43 AM CET 
//


package no.nav.melding.domene.brukerdialog.behandlingsinformasjon.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.joda.time.DateTime;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for melding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="melding">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1}faktum">
 *       &lt;sequence>
 *         &lt;element name="aktor" type="{http://nav.no/melding/domene/brukerdialog/behandlingsinformasjon/v1}aktor" minOccurs="0"/>
 *         &lt;element name="meldingstekst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="temastruktur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="traad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lestDato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="opprettetDato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "melding", propOrder = {
    "aktor",
    "meldingstekst",
    "temastruktur",
    "traad",
    "lestDato",
    "opprettetDato"
})
public class XMLMelding
    extends XMLFaktum
{

    protected XMLAktor aktor;
    protected String meldingstekst;
    protected String temastruktur;
    protected String traad;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime lestDato;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime opprettetDato;

    /**
     * Gets the value of the aktor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAktor }
     *     
     */
    public XMLAktor getAktor() {
        return aktor;
    }

    /**
     * Sets the value of the aktor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAktor }
     *     
     */
    public void setAktor(XMLAktor value) {
        this.aktor = value;
    }

    /**
     * Gets the value of the meldingstekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeldingstekst() {
        return meldingstekst;
    }

    /**
     * Sets the value of the meldingstekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeldingstekst(String value) {
        this.meldingstekst = value;
    }

    /**
     * Gets the value of the temastruktur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemastruktur() {
        return temastruktur;
    }

    /**
     * Sets the value of the temastruktur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemastruktur(String value) {
        this.temastruktur = value;
    }

    /**
     * Gets the value of the traad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraad() {
        return traad;
    }

    /**
     * Sets the value of the traad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraad(String value) {
        this.traad = value;
    }

    /**
     * Gets the value of the lestDato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getLestDato() {
        return lestDato;
    }

    /**
     * Sets the value of the lestDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLestDato(DateTime value) {
        this.lestDato = value;
    }

    /**
     * Gets the value of the opprettetDato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getOpprettetDato() {
        return opprettetDato;
    }

    /**
     * Sets the value of the opprettetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpprettetDato(DateTime value) {
        this.opprettetDato = value;
    }

}
