<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4" location="Organisasjon.wsdl">
    </wsdl:import>
  <wsdl:binding name="OrganisasjonBinding" type="wsdl_1:TsswsOrganisasjon_v4">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="finnOrganisasjonsendringerListe">
      <soap:operation soapAction="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4/TsswsOrganisasjon_v4/finnOrganisasjonsendringerListeRequest" style="document"/>
      <wsdl:input name="finnOrganisasjonsendringerListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="finnOrganisasjonsendringerListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentOrganisasjon">
      <soap:operation soapAction="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4/TsswsOrganisasjon_v4/hentOrganisasjonRequest" style="document"/>
      <wsdl:input name="hentOrganisasjonRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentOrganisasjonResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="organisasjonIkkeFunnet">
        <soap:fault name="organisasjonIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/fellesregistre/tssws_organisasjon/v4/TsswsOrganisasjon_v4/pingRequest" style="document"/>
      <wsdl:input name="pingRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="pingResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TsswsOrganisasjon_v4">
    <wsdl:port name="TsswsOrganisasjonPort" binding="tns:OrganisasjonBinding">
      <soap:address location="http://localhost:9080/tssws/TsswsOrganisasjon_v4"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
