<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PersonWSEXP_PersonHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/person/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/person/v1">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/person/v1" location="no/nav/virksomhet/tjenester/person/person.wsdl">
    </wsdl:import>
  <wsdl:binding name="PersonWSEXP_PersonHttpBinding" type="this:Person">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="registrereAdresseForDodsbo">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/person/v1/registrereAdresseForDodsbo"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="personHarUtlandsadresse">
        <soap:fault name="personHarUtlandsadresse" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="kunneIkkeRegistrereAdresseForDodsbo">
        <soap:fault name="kunneIkkeRegistrereAdresseForDodsbo" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentPerson">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/person/v1/hentPerson"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PersonIkkeFunnet">
        <soap:fault name="PersonIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentUtenlandskIdentitetListe">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/person/v1/hentUtenlandskIdentitetListe"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="personIkkeFunnet">
        <soap:fault name="personIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PersonWSEXP_PersonHttpService">
    <wsdl:port name="PersonWSEXP_PersonHttpPort" binding="this:PersonWSEXP_PersonHttpBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-person_v1Web/sca/PersonWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
