<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="DownloadQueueExternalBasic"
                  targetNamespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://www.altinn.no/services/Archive/DownloadQueue/2012/08"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl">
    <wsp:Policy wsu:Id="BasicHttpBinding_IDownloadQueueExternalBasic_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization
                        xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/2009/10">
            <xsd:element name="Test">
                <xsd:complexType>
                    <xsd:sequence/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="TestResponse">
                <xsd:complexType>
                    <xsd:sequence/>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/common/fault/2009/10"
                    xmlns:tns="http://www.altinn.no/services/common/fault/2009/10">
            <xsd:complexType name="AltinnFault">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a SOAP fault message used by Altinn to convey exception information to the
                                caller.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="AltinnErrorMessage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the error message.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AltinnExtendedErrorMessage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the verbose version of the error message.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AltinnLocalizedErrorMessage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the localized version of the error message.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ErrorGuid" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the unique GUID for the specific fault.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ErrorID" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the error type id.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="UserGuid" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the GUID of the user.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="UserId" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the id of the user.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="AltinnFault" nillable="true" type="tns:AltinnFault"/>
        </xsd:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
                   targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08">
            <xsd:import namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08"/>
            <xsd:import namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08"/>
            <xsd:element name="GetArchivedFormTaskBasicDQ">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="systemUserName" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="systemPassword" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="archiveReference" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="languageID" nillable="true" type="xsd:int"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="GetArchivedFormTaskBasicDQResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="GetArchivedFormTaskBasicDQResult" nillable="true"
                                     type="q1:ArchivedFormTaskDQBE"
                                     xmlns:q1="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="GetDownloadQueueItems">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="systemUserName" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="systemPassword" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="serviceCode" nillable="true" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="GetDownloadQueueItemsResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="GetDownloadQueueItemsResult" nillable="true"
                                     type="q2:DownloadQueueItemBEList"
                                     xmlns:q2="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="PurgeItem">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="systemUserName" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="systemPassword" nillable="true" type="xsd:string"/>
                        <xsd:element minOccurs="0" name="archiveReference" nillable="true" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="PurgeItemResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="PurgeItemResult" nillable="true" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="GetFormSetPdfBasic">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="1" name="systemName" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="systemPassword" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="archiveReference" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="languageId" type="xsd:int"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="GetFormSetPdfBasicResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="GetFormSetPdfBasicResult" nillable="true"
                                     type="xsd:base64Binary"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08"
                    xmlns:tns="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08">
            <xsd:import namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08"/>
            <xsd:import namespace="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive"/>
            <xsd:complexType name="ArchivedFormTaskDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represent an archived form task for download queue.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="Approvers" nillable="true" type="tns:ApproverListDQBE">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets list of approvers.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ArchiveReference" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the archive reference for the archived form task.
                                        Archive reference is reportee element id with letters 'AR' added.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ArchiveTimeStamp" type="xsd:dateTime">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets date and time when the form task was archived.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="Attachments" nillable="true"
                                 type="tns:ArchivedAttachmentExternalListDQBE">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets list of archived attachments for archived form task.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AttachmentsInResponse" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the number of attachments in the form task.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="CaseID" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the case id for collaboration.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="CorrelationReference" type="xsd:long">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the correlation reference.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="Forms" nillable="true" type="tns:ArchivedFormListDQBE">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets list of archived forms in the archived form task.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="FormsInResponse" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the number of forms in the form task.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="Reportee" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets reportee for the archived form task.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="SOEncryptedSymmetricKey" nillable="true"
                                 type="q3:SOEncryptedSymmetricKeyExternalDQBE"
                                 xmlns:q3="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets symmetrical key for service owner encryption.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ServiceCode" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the external service code.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ServiceEditionCode" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the external service edition code.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ArchivedFormTaskDQBE" nillable="true" type="tns:ArchivedFormTaskDQBE"/>
            <xsd:complexType name="ApproverListDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed collection of ApproverDQBE
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="ApproverDQBE" nillable="true"
                                 type="tns:ApproverDQBE"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ApproverListDQBE" nillable="true" type="tns:ApproverListDQBE"/>
            <xsd:complexType name="ApproverDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents limited signature data
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="ApprovedTimeStamp" type="xsd:dateTime">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the approved time stamp.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ApproverID" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the userID of the approver.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="SecurityLevel" type="q4:ApproverSecurityLevel"
                                 xmlns:q4="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the security level. The security level is the AuthenticationLevel.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ApproverDQBE" nillable="true" type="tns:ApproverDQBE"/>
            <xsd:complexType name="ArchivedAttachmentExternalListDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed collection of ArchivedAttachmentDQBE
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="ArchivedAttachmentDQBE" nillable="true"
                                 type="tns:ArchivedAttachmentDQBE"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ArchivedAttachmentExternalListDQBE" nillable="true"
                         type="tns:ArchivedAttachmentExternalListDQBE"/>
            <xsd:complexType name="ArchivedAttachmentDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents data for archived attachment for download queue.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="ArchiveReference" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the archive reference of the attachment.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AttachmentData" nillable="true" type="xsd:base64Binary">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the attachment data.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AttachmentType" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the type of the attachment.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="FileName" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the filename of the attachment.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="IsEncrypted" type="xsd:boolean">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a value indicating whether the attachment is encrypted or not.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AttachmentId" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the the unique id of the attachment in Altinn.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AttachmentTypeName" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the technical name of the attachment rule associated with the
                                        attachment.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AttachmentTypeNameLanguage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the translated name of the attachment rule associated with the
                                        attachment.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ArchivedAttachmentDQBE" nillable="true" type="tns:ArchivedAttachmentDQBE"/>
            <xsd:complexType name="ArchivedFormListDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed collection of ArchivedFormDQBE
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="ArchivedFormDQBE" nillable="true"
                                 type="tns:ArchivedFormDQBE"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ArchivedFormListDQBE" nillable="true" type="tns:ArchivedFormListDQBE"/>
            <xsd:complexType name="ArchivedFormDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents data for archived form for download queue.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="DataFormatID" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets identifier for the data format.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="DataFormatVersionID" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets version of data format.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="FormData" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the form data XML.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ParentReference" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the parent information of the form.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="Reference" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets identifier used to identify FormID.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ArchivedFormDQBE" nillable="true" type="tns:ArchivedFormDQBE"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08"
                    xmlns:tns="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08">
            <xsd:import namespace="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive"/>
            <xsd:complexType name="SOEncryptedSymmetricKeyExternalDQBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents data contract for key management instances for external usage.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="CertificateThumbprint" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the thumb print for the certificate used for decryption
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="EncryptedKey" nillable="true" type="xsd:base64Binary">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the AES crypto key
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="SOEncryptedSymmetricKeyExternalDQBE" nillable="true"
                         type="tns:SOEncryptedSymmetricKeyExternalDQBE"/>
            <xsd:complexType name="DownloadQueueItemBEList">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed collection of DownloadQueueItemExternalBE.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="DownloadQueueItemBE" nillable="true"
                                 type="tns:DownloadQueueItemBE"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="DownloadQueueItemBEList" nillable="true" type="tns:DownloadQueueItemBEList"/>
            <xsd:complexType name="DownloadQueueItemBE">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents item in download queue.
                                &lt;/summary&gt;</d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="ArchiveReference" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the archive reference for the item.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ArchivedDate" type="xsd:dateTime">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the date and time when the item was archived.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReporteeID" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the unique identifier of the reportee for the item..
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReporteeType" type="q5:DownloadQueueReporteeType"
                                 xmlns:q5="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the reportee type for the item.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ServiceCode" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets service code for for the item.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ServiceEditionCode" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets service edition code for the item.
                                        &lt;/summary&gt;</d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="DownloadQueueItemBE" nillable="true" type="tns:DownloadQueueItemBE"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive"
                    xmlns:tns="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive">
            <xsd:simpleType name="ApproverSecurityLevel">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:EnumAnnotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:EnumText z:Id="2">&lt;summary&gt;
                                Specifies different authentication levels of a signee or approver.
                                &lt;/summary&gt;</d1p1:EnumText>
                            <d1p1:Members z:Id="3" z:Size="5"
                                          xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="4">selfIdentifiedUser</d2p1:Key>
                                    <d2p1:Value z:Id="5">&lt;summary&gt;
                                        Specifies that signee was self identified.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="6">notSensitive</d2p1:Key>
                                    <d2p1:Value z:Id="7">&lt;summary&gt;
                                        Specifies that signee had authentication level for data with no sensitivity.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="8">lessSensitive</d2p1:Key>
                                    <d2p1:Value z:Id="9">&lt;summary&gt;
                                        Specifies that signee had authentication level for data with less sensitivity.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="10">sensitive</d2p1:Key>
                                    <d2p1:Value z:Id="11">&lt;summary&gt;
                                        Specifies that signee had authentication level for data that are sensitive.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="12">verySensitive</d2p1:Key>
                                    <d2p1:Value z:Id="13">&lt;summary&gt;
                                        Specifies that signee had authentication level for data with high sensitivity.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                            </d1p1:Members>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="selfIdentifiedUser"/>
                    <xsd:enumeration value="notSensitive"/>
                    <xsd:enumeration value="lessSensitive"/>
                    <xsd:enumeration value="sensitive"/>
                    <xsd:enumeration value="verySensitive"/>
                </xsd:restriction>
            </xsd:simpleType>
            <xsd:element name="ApproverSecurityLevel" nillable="true" type="tns:ApproverSecurityLevel"/>
            <xsd:simpleType name="DownloadQueueReporteeType">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:EnumAnnotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:EnumText z:Id="2">&lt;summary&gt;
                                Specifies different reportee types.
                                &lt;/summary&gt;</d1p1:EnumText>
                            <d1p1:Members z:Id="3" z:Size="3"
                                          xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="4">Organisation</d2p1:Key>
                                    <d2p1:Value z:Id="5">&lt;summary&gt;
                                        Reportee is an organization.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="6">Person</d2p1:Key>
                                    <d2p1:Value z:Id="7">&lt;summary&gt;
                                        Reportee is a person.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="8">Selfregistereduser</d2p1:Key>
                                    <d2p1:Value z:Id="9">&lt;summary&gt;
                                        Reportee is a self identified user.
                                        &lt;/summary&gt;</d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                            </d1p1:Members>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Organisation"/>
                    <xsd:enumeration value="Person"/>
                    <xsd:enumeration value="Selfregistereduser"/>
                </xsd:restriction>
            </xsd:simpleType>
            <xsd:element name="DownloadQueueReporteeType" nillable="true" type="tns:DownloadQueueReporteeType"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="IDownloadQueueExternalBasic_Test_InputMessage">
        <wsdl:part name="parameters" element="q6:Test" xmlns:q6="http://www.altinn.no/services/2009/10"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_Test_OutputMessage">
        <wsdl:part name="parameters" element="q7:TestResponse" xmlns:q7="http://www.altinn.no/services/2009/10"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_Test_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q8:AltinnFault"
                   xmlns:q8="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetArchivedFormTaskBasicDQ_InputMessage">
        <wsdl:part name="parameters" element="tns:GetArchivedFormTaskBasicDQ"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetArchivedFormTaskBasicDQ_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetArchivedFormTaskBasicDQResponse"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetArchivedFormTaskBasicDQ_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q9:AltinnFault"
                   xmlns:q9="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetDownloadQueueItems_InputMessage">
        <wsdl:part name="parameters" element="tns:GetDownloadQueueItems"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetDownloadQueueItems_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetDownloadQueueItemsResponse"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetDownloadQueueItems_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q10:AltinnFault"
                   xmlns:q10="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_PurgeItem_InputMessage">
        <wsdl:part name="parameters" element="tns:PurgeItem"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_PurgeItem_OutputMessage">
        <wsdl:part name="parameters" element="tns:PurgeItemResponse"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_PurgeItem_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q11:AltinnFault"
                   xmlns:q11="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetFormSetPdfBasic_InputMessage">
        <wsdl:part name="parameters" element="tns:GetFormSetPdfBasic"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetFormSetPdfBasic_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetFormSetPdfBasicResponse"/>
    </wsdl:message>
    <wsdl:message name="IDownloadQueueExternalBasic_GetFormSetPdfBasic_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q12:AltinnFault"
                   xmlns:q12="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:portType name="IDownloadQueueExternalBasic">
        <wsdl:documentation>&lt;summary&gt;&#xD;
            This contract defines the external basic binding contract for DownloadQueueExternalBasic service.&#xD;
            &lt;/summary&gt;</wsdl:documentation>
        <wsdl:operation name="Test">
            <wsdl:input wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test"
                        message="tns:IDownloadQueueExternalBasic_Test_InputMessage"/>
            <wsdl:output wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse"
                         message="tns:IDownloadQueueExternalBasic_Test_OutputMessage"/>
            <wsdl:fault wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault"
                        name="AltinnFaultFault"
                        message="tns:IDownloadQueueExternalBasic_Test_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="GetArchivedFormTaskBasicDQ">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                Retrieve an ArchivedFormTaskBE object containing all forms and attachments&#xD;
                for the specific form task based on the reportee elementId provided.&#xD;
                &lt;/summary&gt;&#xD;
                &lt;remarks&gt;&#xD;
                This operation is versioned as V2 as it contains some additional information. Preferred over Get
                Archived Form Task Basic.&#xD;
                &lt;/remarks&gt;&#xD;
                &lt;param name="systemUserName"&gt;&#xD;
                System user name is the relevant agency system name that is registered in Altinn - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                System password is the password for the corresponding registered agency system - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="archiveReference"&gt;&#xD;
                Identifier for a Reportee Element to get, this consists of the letters "AR" followed by the
                ReporteeElementID -&#xD;
                mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="languageID"&gt;&#xD;
                Localization Language (English 1033, Bokmål 1044, Nynorsk 2068) - optional parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;returns&gt;&#xD;
                Archived Form Task entity&#xD;
                &lt;/returns&gt;</wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetArchivedFormTaskBasicDQ"
                    message="tns:IDownloadQueueExternalBasic_GetArchivedFormTaskBasicDQ_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetArchivedFormTaskBasicDQResponse"
                    message="tns:IDownloadQueueExternalBasic_GetArchivedFormTaskBasicDQ_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetArchivedFormTaskBasicDQAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IDownloadQueueExternalBasic_GetArchivedFormTaskBasicDQ_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="GetDownloadQueueItems">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                Gets a list of up to 500 DownloadQueue items. Filters based on serviceCode.&#xD;
                &lt;/summary&gt;&#xD;
                &lt;param name="systemUserName"&gt;&#xD;
                contains the system User Name&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                contains the system password.&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="serviceCode"&gt;&#xD;
                The service code that you want to filter DownloadQueue items by. - Optional parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;returns&gt;&#xD;
                A list of up to 500 DownloadQueue items.&#xD;
                &lt;/returns&gt;</wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetDownloadQueueItems"
                    message="tns:IDownloadQueueExternalBasic_GetDownloadQueueItems_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetDownloadQueueItemsResponse"
                    message="tns:IDownloadQueueExternalBasic_GetDownloadQueueItems_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetDownloadQueueItemsAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IDownloadQueueExternalBasic_GetDownloadQueueItems_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="PurgeItem">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                Marks DownloadQueue item as Purged.&#xD;
                &lt;/summary&gt;&#xD;
                &lt;param name="systemUserName"&gt;&#xD;
                contains the system User Name&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                contains the system password.&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="archiveReference"&gt;&#xD;
                Archive reference&#xD;
                &lt;/param&gt;&#xD;
                &lt;returns&gt;&#xD;
                Purge item as string&#xD;
                &lt;/returns&gt;</wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/PurgeItem"
                    message="tns:IDownloadQueueExternalBasic_PurgeItem_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/PurgeItemResponse"
                    message="tns:IDownloadQueueExternalBasic_PurgeItem_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/PurgeItemAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IDownloadQueueExternalBasic_PurgeItem_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="GetFormSetPdfBasic">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                This method provides a PDF version of a form set.&#xD;
                &lt;/summary&gt;&#xD;
                &lt;param name="systemName"&gt;&#xD;
                The user name for the agency system.&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                The password for the agency system.&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="archiveReference"&gt;&#xD;
                The archive reference for the archived element to retrieve PDF for.&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="languageId"&gt;The language to use on translated text.&lt;/param&gt;&#xD;
                &lt;returns&gt;&#xD;
                Returns the PDF as binary.&#xD;
                &lt;/returns&gt;</wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetFormSetPdfBasic"
                    message="tns:IDownloadQueueExternalBasic_GetFormSetPdfBasic_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetFormSetPdfBasicResponse"
                    message="tns:IDownloadQueueExternalBasic_GetFormSetPdfBasic_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetFormSetPdfBasicAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:IDownloadQueueExternalBasic_GetFormSetPdfBasic_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_IDownloadQueueExternalBasic" type="tns:IDownloadQueueExternalBasic">
        <wsp:PolicyReference URI="#BasicHttpBinding_IDownloadQueueExternalBasic_policy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Test">
            <soap:operation soapAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test"
                            style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="GetArchivedFormTaskBasicDQ">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetArchivedFormTaskBasicDQ"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="GetDownloadQueueItems">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetDownloadQueueItems"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="PurgeItem">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/PurgeItem"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="GetFormSetPdfBasic">
            <soap:operation
                    soapAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExternalBasic/GetFormSetPdfBasic"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DownloadQueueExternalBasic">
        <wsdl:port name="BasicHttpBinding_IDownloadQueueExternalBasic"
                   binding="tns:BasicHttpBinding_IDownloadQueueExternalBasic">
            <soap:address location="http://tt02.altinn.basefarm.net/ArchiveExternal/DownloadQueueExternalBasic.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>