<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding"
				  targetNamespace="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1/Binding"
				  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:wsdl_1="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1"
				  xmlns:tns="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1/Binding"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<wsdl:import namespace="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1"
				 location="sanntidPdfKonverterer.wsdl"/>

	<wsdl:binding name="sanntidPdfKonvertererBinding" type="wsdl_1:sanntidPdfKonverterer_v1">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsaw:UsingAddressing/>
		<wsdl:operation name="konverterPdf2Bilde">
			<soap:operation
					soapAction="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1/konverterPdf2Bilde"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="konverterBilde2Pdf">
			<soap:operation
					soapAction="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1/konverterBilde2Pdf"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ping">
			<soap:operation soapAction="http://nav.no/tjeneste/domene/brevogarkiv/sanntidPdfKonverterer/v1/ping"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="sanntidPdfKonvertererService_v1">
		<wsdl:port binding="tns:sanntidPdfKonvertererBinding" name="sanntidPdfKonvertererPort_v1">
			<soap:address location="http://localhost:8098/dokkonv/ws/SanntidPdfKonverterer/v1"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
