<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GOSYSInfotrygdSakWSEXP_GOSYSInfotrygdSakHttp_Service" targetNamespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdSak/Binding" xmlns:Port_0="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdSak" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdSak/Binding">
  <wsdl:import namespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdSak" location="no/nav/inf/GOSYSInfotrygdSak.wsdl">
    </wsdl:import>
  <wsdl:binding name="GOSYSInfotrygdSakWSEXP_GOSYSInfotrygdSakHttpBinding" type="Port_0:GOSYSInfotrygdSak">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="bestillInfotrygdSak">
      <soap:operation soapAction=""/>
      <wsdl:input name="bestillInfotrygdSakRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="bestillInfotrygdSakResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGOSYSUgyldigEnhet">
        <soap:fault name="faultGOSYSUgyldigEnhet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentSakListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentSakListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentSakListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GOSYSInfotrygdSakWSEXP_GOSYSInfotrygdSakHttpService">
    <wsdl:port name="GOSYSInfotrygdSakWSEXP_GOSYSInfotrygdSakHttpPort" binding="this:GOSYSInfotrygdSakWSEXP_GOSYSInfotrygdSakHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-sak-gosys-3.0.0Web/sca/GOSYSInfotrygdSakWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
