//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.18 at 04:46:59 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nav.no/melding/virksomhet/henvendelsebehandling/behandlingsresultat/v1")
package no.nav.melding.virksomhet.henvendelsebehandling.behandlingsresultat.v1;
