<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/innsynJournal/v2/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/virksomhet/innsynJournal/v2/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/innsynJournal/v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/innsynJournal/v2" location="innsynJournal.wsdl">
    </wsdl:import>
  <wsdl:binding name="InnsynJournal_v2Binding" type="wsdl_1:InnsynJournal_v2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/innsynJournal/v2/InnsynJournal_v2/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="hentTilgjengeligJournalpostListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/innsynJournal/v2/InnsynJournal_v2/hentTilgjengeligJournalpostListeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="identifiserJournalpost">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/innsynJournal/v2/InnsynJournal_v2/identifiserJournalpostRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="objektIkkeFunnet">
        <soap:fault name="objektIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="gyldigAntallJournalposter">
        <soap:fault name="gyldigAntallJournalposter" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="journalpostIkkeInngaaende">
        <soap:fault name="journalpostIkkeInngaaende" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentDokument">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/innsynJournal/v2/InnsynJournal_v2/hentDokumentRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="dokumentIkkeFunnet">
        <soap:fault name="dokumentIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="InnsynJournal_v2">
    <wsdl:port name="InnsynJournal_v2Port" binding="tns:InnsynJournal_v2Binding">
      <soap:address location="http://localhost:9080/virksomhet/innsynJournal_v2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
