<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://schemas.nhn.no/reg/HPRv2" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://schemas.nhn.no/reg/HPRv2" name="HPRService2">
	<wsdl:types>
		<xs:schema targetNamespace="http://schemas.nhn.no/reg/HPRv2" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
			<xs:import namespace="http://schemas.nhn.no/reg/Common/no"/>
			<xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
			<xs:complexType name="Person">
				<xs:sequence>
					<xs:element name="AlternativeIder" type="tns:ArrayOfAlternativId" minOccurs="0" nillable="true"/>
					<xs:element name="Dødsdato" type="xs:dateTime" minOccurs="0" nillable="true"/>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="ErstattetAvHprNummer" minOccurs="0" nillable="true" type="xs:int"/>
					<xs:element name="Etternavn" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Fornavn" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="FysiskeAdresser" type="q1:ArrayOfFysiskAdresse" minOccurs="0" nillable="true" xmlns:q1="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Fødselsdato" type="xs:dateTime" minOccurs="0" nillable="true"/>
					<xs:element name="Godkjenninger" type="tns:ArrayOfGodkjenning" minOccurs="0" nillable="true"/>
					<xs:element name="HPRNummer" type="xs:int" minOccurs="0"/>
					<xs:element name="Kjønn" type="q2:Kode" minOccurs="0" nillable="true" xmlns:q2="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="ManglerNIN" type="xs:boolean" minOccurs="0"/>
					<xs:element name="Mellomnavn" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="NIN" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="SistOppdatert" type="xs:dateTime" minOccurs="0"/>
					<xs:element name="Statsborgerskap" type="q3:Kode" minOccurs="0" nillable="true" xmlns:q3="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Utdannelser" type="tns:ArrayOfUtdannelse" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Person" type="tns:Person" nillable="true"/>
			<xs:complexType name="ArrayOfAlternativId">
				<xs:sequence>
					<xs:element name="AlternativId" type="tns:AlternativId" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfAlternativId" type="tns:ArrayOfAlternativId" nillable="true"/>
			<xs:complexType name="AlternativId">
				<xs:sequence>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Type" type="q4:Kode" minOccurs="0" nillable="true" xmlns:q4="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Verdi" type="xs:string" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="AlternativId" type="tns:AlternativId" nillable="true"/>
			<xs:complexType name="ArrayOfGodkjenning">
				<xs:sequence>
					<xs:element name="Godkjenning" type="tns:Godkjenning" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfGodkjenning" type="tns:ArrayOfGodkjenning" nillable="true"/>
			<xs:complexType name="Godkjenning">
				<xs:sequence>
					<xs:element name="Autorisasjon" type="q5:Kode" minOccurs="0" nillable="true" xmlns:q5="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="AvsluttetStatus" type="q6:Kode" minOccurs="0" nillable="true" xmlns:q6="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="GodkjentTurnus" type="xs:dateTime" minOccurs="0" nillable="true"/>
					<xs:element name="Gyldig" type="q7:Periode" minOccurs="0" nillable="true" xmlns:q7="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Helsepersonellkategori" type="q8:Kode" minOccurs="0" nillable="true" xmlns:q8="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="KonvertertFraLand" type="q9:Kode" minOccurs="0" nillable="true" xmlns:q9="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Rekvisisjonsretter" type="tns:ArrayOfRekvisisjonsrett" minOccurs="0" nillable="true"/>
					<xs:element name="Spesialiteter" type="tns:ArrayOfSpesialitet" minOccurs="0" nillable="true"/>
					<xs:element name="Suspensjonsperioder" type="tns:ArrayOfSuspensjonsperiode" minOccurs="0" nillable="true"/>
					<xs:element name="Tilleggskompetanser" type="tns:ArrayOfTilleggskompetanse" minOccurs="0" nillable="true"/>
					<xs:element name="Utdannelser" type="tns:ArrayOfUtdannelse" minOccurs="0" nillable="true"/>
					<xs:element name="Vilkår" type="tns:ArrayOfVilkår" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Godkjenning" type="tns:Godkjenning" nillable="true"/>
			<xs:complexType name="ArrayOfRekvisisjonsrett">
				<xs:sequence>
					<xs:element name="Rekvisisjonsrett" type="tns:Rekvisisjonsrett" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfRekvisisjonsrett" type="tns:ArrayOfRekvisisjonsrett" nillable="true"/>
			<xs:complexType name="Rekvisisjonsrett">
				<xs:sequence>
					<xs:element name="AvsluttetStatus" type="q10:Kode" minOccurs="0" nillable="true" xmlns:q10="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Gyldig" type="q11:Periode" minOccurs="0" nillable="true" xmlns:q11="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Suspensjonsperioder" type="tns:ArrayOfSuspensjonsperiode" minOccurs="0" nillable="true"/>
					<xs:element name="Type" type="q12:Kode" minOccurs="0" nillable="true" xmlns:q12="http://schemas.nhn.no/reg/Common/no"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Rekvisisjonsrett" type="tns:Rekvisisjonsrett" nillable="true"/>
			<xs:complexType name="ArrayOfSuspensjonsperiode">
				<xs:sequence>
					<xs:element name="Suspensjonsperiode" type="tns:Suspensjonsperiode" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfSuspensjonsperiode" type="tns:ArrayOfSuspensjonsperiode" nillable="true"/>
			<xs:complexType name="Suspensjonsperiode">
				<xs:sequence>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Periode" type="q13:Periode" minOccurs="0" nillable="true" xmlns:q13="http://schemas.nhn.no/reg/Common/no"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Suspensjonsperiode" type="tns:Suspensjonsperiode" nillable="true"/>
			<xs:complexType name="ArrayOfSpesialitet">
				<xs:sequence>
					<xs:element name="Spesialitet" type="tns:Spesialitet" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfSpesialitet" type="tns:ArrayOfSpesialitet" nillable="true"/>
			<xs:complexType name="Spesialitet">
				<xs:sequence>
					<xs:element name="AvsluttetStatus" type="q14:Kode" minOccurs="0" nillable="true" xmlns:q14="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Gyldig" type="q15:Periode" minOccurs="0" nillable="true" xmlns:q15="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="KonvertertFraLand" type="q16:Kode" minOccurs="0" nillable="true" xmlns:q16="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Suspensjonsperioder" type="tns:ArrayOfSuspensjonsperiode" minOccurs="0" nillable="true"/>
					<xs:element name="Type" type="q17:Kode" minOccurs="0" nillable="true" xmlns:q17="http://schemas.nhn.no/reg/Common/no"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Spesialitet" type="tns:Spesialitet" nillable="true"/>
			<xs:complexType name="ArrayOfTilleggskompetanse">
				<xs:sequence>
					<xs:element name="Tilleggskompetanse" type="tns:Tilleggskompetanse" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfTilleggskompetanse" type="tns:ArrayOfTilleggskompetanse" nillable="true"/>
			<xs:complexType name="Tilleggskompetanse">
				<xs:sequence>
					<xs:element name="AvsluttetStatus" type="q18:Kode" minOccurs="0" nillable="true" xmlns:q18="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Gyldig" type="q19:Periode" minOccurs="0" nillable="true" xmlns:q19="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Type" type="q20:Kode" minOccurs="0" nillable="true" xmlns:q20="http://schemas.nhn.no/reg/Common/no"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Tilleggskompetanse" type="tns:Tilleggskompetanse" nillable="true"/>
			<xs:complexType name="ArrayOfUtdannelse">
				<xs:sequence>
					<xs:element name="Utdannelse" type="tns:Utdannelse" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfUtdannelse" type="tns:ArrayOfUtdannelse" nillable="true"/>
			<xs:complexType name="Utdannelse">
				<xs:sequence>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Institution" type="tns:Utdanningsinstitusjon" minOccurs="0" nillable="true"/>
					<xs:element name="Land" type="q21:Kode" minOccurs="0" nillable="true" xmlns:q21="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Type" type="q22:Kode" minOccurs="0" nillable="true" xmlns:q22="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Vitnemålsdato" type="xs:dateTime" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Utdannelse" type="tns:Utdannelse" nillable="true"/>
			<xs:complexType name="Utdanningsinstitusjon">
				<xs:sequence>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="FysiskeAdresser" type="q23:ArrayOfFysiskAdresse" minOccurs="0" nillable="true" xmlns:q23="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Navn" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Organisasjonsnummer" type="xs:int" minOccurs="0" nillable="true"/>
					<xs:element name="Type" type="q24:Kode" minOccurs="0" nillable="true" xmlns:q24="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Utdanningsinstitusjonshistorikk" type="tns:ArrayOfUtdanningsinstitusjonshistorikk" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Utdanningsinstitusjon" type="tns:Utdanningsinstitusjon" nillable="true"/>
			<xs:complexType name="ArrayOfUtdanningsinstitusjonshistorikk">
				<xs:sequence>
					<xs:element name="Utdanningsinstitusjonshistorikk" type="tns:Utdanningsinstitusjonshistorikk" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfUtdanningsinstitusjonshistorikk" type="tns:ArrayOfUtdanningsinstitusjonshistorikk" nillable="true"/>
			<xs:complexType name="Utdanningsinstitusjonshistorikk">
				<xs:sequence>
					<xs:element name="Gyldig" type="q25:Periode" minOccurs="0" nillable="true" xmlns:q25="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="Navn" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Organisasjonsnummer" type="xs:int" minOccurs="0" nillable="true"/>
					<xs:element name="Type" type="q26:Kode" minOccurs="0" nillable="true" xmlns:q26="http://schemas.nhn.no/reg/Common/no"/>
					<xs:element name="YtterligereInformasjon" type="xs:string" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Utdanningsinstitusjonshistorikk" type="tns:Utdanningsinstitusjonshistorikk" nillable="true"/>
			<xs:complexType name="ArrayOfVilkår">
				<xs:sequence>
					<xs:element name="Vilkår" type="tns:Vilkår" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfVilkår" type="tns:ArrayOfVilkår" nillable="true"/>
			<xs:complexType name="Vilkår">
				<xs:sequence>
					<xs:element name="ETag" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Fritekst" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Type" type="q27:Kode" minOccurs="0" nillable="true" xmlns:q27="http://schemas.nhn.no/reg/Common/no"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Vilkår" type="tns:Vilkår" nillable="true"/>
			<xs:element name="HentPersonMedPersonnummer">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="personNummer" type="xs:string" minOccurs="0" nillable="true"/>
						<xs:element name="påTidspunkt" type="xs:dateTime" minOccurs="0" nillable="true"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="HentPersonMedPersonnummerResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="HentPersonMedPersonnummerResult" type="tns:Person" minOccurs="0" nillable="true"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:complexType name="ArrayOfPerson">
				<xs:sequence>
					<xs:element name="Person" type="tns:Person" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfPerson" type="tns:ArrayOfPerson" nillable="true"/>
			<xs:complexType name="ArrayOfEndringslogginnslag">
				<xs:sequence>
					<xs:element name="Endringslogginnslag" type="tns:Endringslogginnslag" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfEndringslogginnslag" type="tns:ArrayOfEndringslogginnslag" nillable="true"/>
			<xs:complexType name="Endringslogginnslag">
				<xs:sequence>
					<xs:element name="BrukersVirksomhet" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="EndredeEntiteter" type="tns:ArrayOfEndretEntitet" minOccurs="0" nillable="true"/>
					<xs:element name="FaktiskBruker" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="Sporingsgruppe" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Sporingsveri" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Tidspunkt" type="xs:dateTime" minOccurs="0"/>
					<xs:element name="Tjenestebruker" type="xs:string" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Endringslogginnslag" type="tns:Endringslogginnslag" nillable="true"/>
			<xs:complexType name="ArrayOfEndretEntitet">
				<xs:sequence>
					<xs:element name="EndretEntitet" type="tns:EndretEntitet" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfEndretEntitet" type="tns:ArrayOfEndretEntitet" nillable="true"/>
			<xs:complexType name="EndretEntitet">
				<xs:sequence>
					<xs:element name="EndredeVerdier" type="tns:ArrayOfEndretVerdi" minOccurs="0" nillable="true"/>
					<xs:element name="EndringsType" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="EntitetsIder" type="q46:ArrayOfstring" minOccurs="0" nillable="true" xmlns:q46="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
					<xs:element name="EntitetsType" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="EndretEntitet" type="tns:EndretEntitet" nillable="true"/>
			<xs:complexType name="ArrayOfEndretVerdi">
				<xs:sequence>
					<xs:element name="EndretVerdi" type="tns:EndretVerdi" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfEndretVerdi" type="tns:ArrayOfEndretVerdi" nillable="true"/>
			<xs:complexType name="EndretVerdi">
				<xs:sequence>
					<xs:element name="GammelVerdi" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Id" type="xs:int" minOccurs="0"/>
					<xs:element name="NyVerdi" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="VerdiNavn" type="xs:string" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="EndretVerdi" type="tns:EndretVerdi" nillable="true"/>
			<xs:complexType name="EksportFormat">
				<xs:sequence>
					<xs:element name="Type" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Versjon" type="xs:int" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="EksportFormat" type="tns:EksportFormat" nillable="true"/>
			<xs:element name="Ping">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="requestId" type="xs:string" minOccurs="0" nillable="true"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="PingResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="PingResult" type="xs:string" minOccurs="0" nillable="true"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="HentRegisterEndringer">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="fra" type="xs:dateTime" minOccurs="0"/>
						<xs:element name="til" type="xs:dateTime" minOccurs="0"/>
						<xs:element name="side" type="xs:int" minOccurs="0"/>
						<xs:element name="resultaterPerSide" type="xs:int" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="HentRegisterEndringerResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="HentRegisterEndringerResult" type="tns:PaginertResultatsett" minOccurs="0" nillable="true"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:complexType name="PaginertResultatsett">
				<xs:sequence>
					<xs:element name="Personer" type="tns:ArrayOfPerson" minOccurs="0" nillable="true"/>
					<xs:element name="ResultaterPerSide" type="xs:int" minOccurs="0"/>
					<xs:element name="ResultaterTotalt" type="xs:int" minOccurs="0"/>
					<xs:element name="Side" type="xs:int" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="PaginertResultatsett" type="tns:PaginertResultatsett" nillable="true"/>
		</xs:schema>
		<xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
			<xs:element name="anyType" type="xs:anyType" nillable="true"/>
			<xs:element name="anyURI" type="xs:anyURI" nillable="true"/>
			<xs:element name="base64Binary" type="xs:base64Binary" nillable="true"/>
			<xs:element name="boolean" type="xs:boolean" nillable="true"/>
			<xs:element name="byte" type="xs:byte" nillable="true"/>
			<xs:element name="dateTime" type="xs:dateTime" nillable="true"/>
			<xs:element name="decimal" type="xs:decimal" nillable="true"/>
			<xs:element name="double" type="xs:double" nillable="true"/>
			<xs:element name="float" type="xs:float" nillable="true"/>
			<xs:element name="int" type="xs:int" nillable="true"/>
			<xs:element name="long" type="xs:long" nillable="true"/>
			<xs:element name="QName" type="xs:QName" nillable="true"/>
			<xs:element name="short" type="xs:short" nillable="true"/>
			<xs:element name="string" type="xs:string" nillable="true"/>
			<xs:element name="unsignedByte" type="xs:unsignedByte" nillable="true"/>
			<xs:element name="unsignedInt" type="xs:unsignedInt" nillable="true"/>
			<xs:element name="unsignedLong" type="xs:unsignedLong" nillable="true"/>
			<xs:element name="unsignedShort" type="xs:unsignedShort" nillable="true"/>
			<xs:element name="char" type="tns:char" nillable="true"/>
			<xs:simpleType name="char">
				<xs:restriction base="xs:int"/>
			</xs:simpleType>
			<xs:element name="duration" type="tns:duration" nillable="true"/>
			<xs:simpleType name="duration">
				<xs:restriction base="xs:duration">
					<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
					<xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
					<xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="guid" type="tns:guid" nillable="true"/>
			<xs:simpleType name="guid">
				<xs:restriction base="xs:string">
					<xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:attribute name="FactoryType" type="xs:QName"/>
			<xs:attribute name="Id" type="xs:ID"/>
			<xs:attribute name="Ref" type="xs:IDREF"/>
		</xs:schema>
		<xs:schema xmlns:tns="http://schemas.nhn.no/reg/Common/no" targetNamespace="http://schemas.nhn.no/reg/Common/no" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
			<xs:complexType name="Kode">
				<xs:sequence>
					<xs:element name="Aktiv" type="xs:boolean" minOccurs="0"/>
					<xs:element name="Beskrivelse" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Kodegruppenavn" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="OID" type="xs:int" minOccurs="0"/>
					<xs:element name="Verdi" type="xs:string" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Kode" type="tns:Kode" nillable="true"/>
			<xs:complexType name="ArrayOfFysiskAdresse">
				<xs:sequence>
					<xs:element name="FysiskAdresse" type="tns:FysiskAdresse" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfFysiskAdresse" type="tns:ArrayOfFysiskAdresse" nillable="true"/>
			<xs:complexType name="FysiskAdresse">
				<xs:sequence>
					<xs:element name="Arvet" type="xs:boolean" minOccurs="0"/>
					<xs:element name="Beskrivelse" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Gateadresse" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Land" type="tns:Kode" minOccurs="0" nillable="true"/>
					<xs:element name="Postboks" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Postkode" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Poststed" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Type" type="tns:Kode" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="FysiskAdresse" type="tns:FysiskAdresse" nillable="true"/>
			<xs:complexType name="Periode">
				<xs:sequence>
					<xs:element name="Fra" type="xs:dateTime" minOccurs="0"/>
					<xs:element name="Til" type="xs:dateTime" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="Periode" type="tns:Periode" nillable="true"/>
			<xs:complexType name="ArrayOfKode">
				<xs:sequence>
					<xs:element name="Kode" type="tns:Kode" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfKode" type="tns:ArrayOfKode" nillable="true"/>
		</xs:schema>
		<xs:schema xmlns:tns="http://register.nhn.no/Common" targetNamespace="http://register.nhn.no/Common" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
			<xs:complexType name="GenericFault">
				<xs:sequence>
					<xs:element name="ErrorCode" type="xs:string" minOccurs="0" nillable="true"/>
					<xs:element name="Message" type="xs:string" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="GenericFault" type="tns:GenericFault" nillable="true"/>
		</xs:schema>
		<xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
			<xs:complexType name="ArrayOfstring">
				<xs:sequence>
					<xs:element name="string" type="xs:string" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfstring" type="tns:ArrayOfstring" nillable="true"/>
			<xs:complexType name="ArrayOfint">
				<xs:sequence>
					<xs:element name="int" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfint" type="tns:ArrayOfint" nillable="true"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="IHPR2Service_HentPersonMedPersonnummer_InputMessage">
		<wsdl:part name="parameters" element="tns:HentPersonMedPersonnummer"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_HentPersonMedPersonnummer_OutputMessage">
		<wsdl:part name="parameters" element="tns:HentPersonMedPersonnummerResponse"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_HentPersonMedPersonnummer_GenericFaultFault_FaultMessage">
		<wsdl:part name="detail" xmlns:q3="http://register.nhn.no/Common" element="q3:GenericFault"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_Ping_InputMessage">
		<wsdl:part name="parameters" element="tns:Ping"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_Ping_OutputMessage">
		<wsdl:part name="parameters" element="tns:PingResponse"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_Ping_GenericFaultFault_FaultMessage">
		<wsdl:part name="detail" element="q48:GenericFault" xmlns:q48="http://register.nhn.no/Common"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_HentRegisterEndringer_InputMessage">
		<wsdl:part name="parameters" element="tns:HentRegisterEndringer"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_HentRegisterEndringer_OutputMessage">
		<wsdl:part name="parameters" element="tns:HentRegisterEndringerResponse"/>
	</wsdl:message>
	<wsdl:message name="IHPR2Service_HentRegisterEndringer_GenericFaultFault_FaultMessage">
		<wsdl:part name="detail" element="q49:GenericFault" xmlns:q49="http://register.nhn.no/Common"/>
	</wsdl:message>
	<wsdl:portType name="IHPR2Service">
		<wsdl:operation name="HentPersonMedPersonnummer">
			<wsdl:input message="tns:IHPR2Service_HentPersonMedPersonnummer_InputMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentPersonMedPersonnummer"/>
			<wsdl:output message="tns:IHPR2Service_HentPersonMedPersonnummer_OutputMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentPersonMedPersonnummerResponse"/>
			<wsdl:fault name="GenericFaultFault" message="tns:IHPR2Service_HentPersonMedPersonnummer_GenericFaultFault_FaultMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentPersonMedPersonnummerGenericFaultFault"/>
		</wsdl:operation>
		<wsdl:operation name="Ping">
			<wsdl:input message="tns:IHPR2Service_Ping_InputMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/Ping"/>
			<wsdl:output message="tns:IHPR2Service_Ping_OutputMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/PingResponse"/>
			<wsdl:fault name="GenericFaultFault" message="tns:IHPR2Service_Ping_GenericFaultFault_FaultMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/PingGenericFaultFault"/>
		</wsdl:operation>
		<wsdl:operation name="HentRegisterEndringer">
			<wsdl:input message="tns:IHPR2Service_HentRegisterEndringer_InputMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentRegisterEndringer"/>
			<wsdl:output message="tns:IHPR2Service_HentRegisterEndringer_OutputMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentRegisterEndringerResponse"/>
			<wsdl:fault name="GenericFaultFault" message="tns:IHPR2Service_HentRegisterEndringer_GenericFaultFault_FaultMessage" wsam:Action="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentRegisterEndringerGenericFaultFault"/>
		</wsdl:operation>
	</wsdl:portType>	
	<wsdl:binding name="BasicHttpBinding_IHPR2Service" type="tns:IHPR2Service">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="HentPersonMedPersonnummer">
			<soap:operation style="document" soapAction="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentPersonMedPersonnummer"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="GenericFaultFault">
				<soap:fault name="GenericFaultFault" namespace="" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="Ping">
			<soap:operation style="document" soapAction="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/Ping"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="GenericFaultFault">
				<soap:fault name="GenericFaultFault" namespace="" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="HentRegisterEndringer">
			<soap:operation style="document" soapAction="http://schemas.nhn.no/reg/HPRv2/IHPR2Service/HentRegisterEndringer"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="GenericFaultFault">
				<soap:fault name="GenericFaultFault" namespace="" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="HPRService2">
		<wsdl:port name="BasicHttpBinding_IHPR2Service" binding="tns:BasicHttpBinding_IHPR2Service">
			<soap:address location="https://ws-web.test.nhn.no/v2/HPR/Basic"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>