<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ArbeidOgAktivitetWSEXP_ArbeidOgAktivitetHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/sak/arbeidogaktivitet/v1/Binding" xmlns:Port_0="http://nav.no/virksomhet/tjenester/sak/arbeidogaktivitet/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/sak/arbeidogaktivitet/v1/Binding">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/sak/arbeidogaktivitet/v1" location="no/nav/virksomhet/tjenester/sak/arbeidogaktivitet/arbeidogaktivitet.wsdl">
    </wsdl:import>
  <wsdl:binding name="ArbeidOgAktivitetWSEXP_ArbeidOgAktivitetHttpBinding" type="Port_0:ArbeidOgAktivitet">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentSakListe">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/sak/arbeidogaktivitet/v1/Binding/hentSakListe"/>
      <wsdl:input>
        <soap:body parts="request" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="response" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ArbeidOgAktivitetWSEXP_ArbeidOgAktivitetHttpService">
    <wsdl:port name="ArbeidOgAktivitetWSEXP_ArbeidOgAktivitetHttpPort" binding="this:ArbeidOgAktivitetWSEXP_ArbeidOgAktivitetHttpBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-arbeidOgAktivitet_v1Web/sca/ArbeidOgAktivitetWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
