<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="NotificationAgencyExternalBasicSF"
                  targetNamespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://www.altinn.no/services/ServiceEngine/Notification/2010/10"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl">
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/2009/10">
            <xsd:element name="Test">
                <xsd:complexType>
                    <xsd:sequence/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="TestResponse">
                <xsd:complexType>
                    <xsd:sequence/>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/common/fault/2009/10"
                    xmlns:tns="http://www.altinn.no/services/common/fault/2009/10">
            <xsd:complexType name="AltinnFault">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a SOAP fault message used by Altinn to convey exception information to the
                                caller.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="AltinnErrorMessage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the error message.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AltinnExtendedErrorMessage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the verbose version of the error message.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="AltinnLocalizedErrorMessage" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the localized version of the error message.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ErrorGuid" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the unique GUID for the specific fault.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ErrorID" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the error type id.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="UserGuid" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the GUID of the user.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="UserId" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the id of the user.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="AltinnFault" nillable="true" type="tns:AltinnFault"/>
        </xsd:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
                   targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10">
            <xsd:import namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10"/>
            <xsd:import namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06"/>
            <xsd:element name="SendStandaloneNotificationBasic">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="1" name="systemUserName" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="systemPassword" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="standaloneNotifications" type="q1:StandaloneNotificationBEList"
                                     xmlns:q1="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="SendStandaloneNotificationBasicResponse">
                <xsd:complexType>
                    <xsd:sequence/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="SendStandaloneNotificationBasicV2">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="1" name="systemUserName" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="systemPassword" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="standaloneNotifications" type="q2:StandaloneNotificationBEList"
                                     xmlns:q2="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="SendStandaloneNotificationBasicV2Response">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="SendStandaloneNotificationBasicV2Result" nillable="true"
                                     type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="SendStandaloneNotificationBasicV3">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="1" name="systemUserName" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="systemPassword" type="xsd:string"/>
                        <xsd:element minOccurs="1" name="standaloneNotifications" type="q3:StandaloneNotificationBEList"
                                     xmlns:q3="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="SendStandaloneNotificationBasicV3Response">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="SendStandaloneNotificationBasicV3Result" nillable="true"
                                     type="q4:SendNotificationResultList"
                                     xmlns:q4="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10"
                    xmlns:tns="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10">
            <xsd:import namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10"/>
            <xsd:complexType name="StandaloneNotificationBEList">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed collection of stand alone notifications.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="StandaloneNotification" nillable="true"
                                 type="q5:StandaloneNotification"
                                 xmlns:q5="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="StandaloneNotificationBEList" nillable="true" type="tns:StandaloneNotificationBEList"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10"
                    xmlns:tns="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10">
            <xsd:import namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06"/>
            <xsd:import namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10"/>
            <xsd:complexType name="StandaloneNotification">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a stand alone notification.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="FromAddress" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the from address.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="IsReservable" nillable="true" type="xsd:boolean">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a value indicating whether it is possible to be reserved against
                                        this specific notification.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="LanguageID" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets language code for the language of the notification.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="NotificationType" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the notification type.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReceiverEndPoints" nillable="true"
                                 type="tns:ReceiverEndPointBEList">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a list of receivers of the notification.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReporteeNumber" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the receiver id.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="Roles" nillable="true" type="q6:Roles"
                                 xmlns:q6="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a collection of Roles. Users with these roles will receive a
                                        Notification. (NOT IMPLEMENTED)
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="Service" nillable="true" type="q7:Service"
                                 xmlns:q7="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the Service info for the StandaloneNotification.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ShipmentDateTime" type="xsd:dateTime">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the date and time for when the notification should be sent.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="TextTokens" nillable="true" type="tns:TextTokenSubstitutionBEList">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a list of replacement tokens. These are used to insert dynamic text
                                        into notification templates.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="UseServiceOwnerShortNameAsSenderOfSms" nillable="true"
                                 type="xsd:boolean">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a value indicating whether the registered shortname of the service
                                        owner should be used to set the name of the sender for SMS notifications
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="StandaloneNotification" nillable="true" type="tns:StandaloneNotification"/>
            <xsd:complexType name="ReceiverEndPointBEList">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed list of ReceiverEndPoint elements that can be accessed by
                                index.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="ReceiverEndPoint" nillable="true"
                                 type="tns:ReceiverEndPoint"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ReceiverEndPointBEList" nillable="true" type="tns:ReceiverEndPointBEList"/>
            <xsd:complexType name="ReceiverEndPoint">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a receiver of a notification.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="TransportType" nillable="true" type="q8:TransportType"
                                 xmlns:q8="http://schemas.altinn.no/serviceengine/formsengine/2009/10">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets what type of transport this receiver end point is. (Email, SMS.)
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReceiverAddress" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the address of the receiver. Email address or mobile phone number.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ReceiverEndPoint" nillable="true" type="tns:ReceiverEndPoint"/>
            <xsd:complexType name="TextTokenSubstitutionBEList">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a strongly typed list of TextToken elements that can be accessed by index.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="TextToken" nillable="true"
                                 type="tns:TextToken"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="TextTokenSubstitutionBEList" nillable="true" type="tns:TextTokenSubstitutionBEList"/>
            <xsd:complexType name="TextToken">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a TextToken. TextTokens is used to create more dynamic notification texts. A
                                Token can trigger text substitution
                                between a token number and a token value.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="TokenNum" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the token number.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="TokenValue" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the token value.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="TextToken" nillable="true" type="tns:TextToken"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06"
                    xmlns:tns="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2015/06">
            <xsd:complexType name="Roles">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                List of Roles in unit that should receive Notifications.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="RoleName" nillable="true" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="Roles" nillable="true" type="tns:Roles"/>
            <xsd:complexType name="Service">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                List of Roles in unit that should receive Notifications.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="ServiceCode" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the ServiceCode. Users who are able to read ReporteeElements with
                                        this ServiceCode for the Reportee will receive a Notification if they're
                                        eligible.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="ServiceEdition" type="xsd:int">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the ServiceCode. Users who are able to read ReporteeElements with
                                        this ServiceCode for the Reportee will receive a Notification if they're
                                        eligible.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="Service" nillable="true" type="tns:Service"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10"
                    xmlns:tns="http://schemas.altinn.no/serviceengine/formsengine/2009/10">
            <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
            <xsd:simpleType name="TransportType">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:EnumAnnotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:EnumText z:Id="2">&lt;summary&gt;
                                Defines types of transportation for sending notifications.
                                &lt;/summary&gt;
                            </d1p1:EnumText>
                            <d1p1:Members z:Id="3" z:Size="6"
                                          xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="4">SMS</d2p1:Key>
                                    <d2p1:Value z:Id="5">&lt;summary&gt;
                                        Specifies that notifications should be sent via SMS.
                                        &lt;/summary&gt;
                                    </d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="6">Email</d2p1:Key>
                                    <d2p1:Value z:Id="7">&lt;summary&gt;
                                        Specifies that notifications should be sent via email.
                                        &lt;/summary&gt;
                                    </d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="8">IM</d2p1:Key>
                                    <d2p1:Value z:Id="9">&lt;summary&gt;
                                        Specifies that notifications should be sent via IM.
                                        &lt;/summary&gt;
                                    </d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="10">Both</d2p1:Key>
                                    <d2p1:Value z:Id="11">&lt;summary&gt;
                                        Specifies that notifications should be sent via both SMS and email.
                                        &lt;/summary&gt;
                                    </d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="12">SMSPreferred</d2p1:Key>
                                    <d2p1:Value z:Id="13">&lt;summary&gt;
                                        Specifies that notifications is preferred to be sent via SMS, but should be sent
                                        by email if no phone number exist.
                                        &lt;/summary&gt;
                                    </d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                                <d2p1:KeyValueOfstringstring>
                                    <d2p1:Key z:Id="14">EmailPreferred</d2p1:Key>
                                    <d2p1:Value z:Id="15">&lt;summary&gt;
                                        Specifies that notifications is preferred to be sent via Email, but should be
                                        sent by SMS, of no email address exist.
                                        &lt;/summary&gt;
                                    </d2p1:Value>
                                </d2p1:KeyValueOfstringstring>
                            </d1p1:Members>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="SMS">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1
                                </EnumerationValue>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="Email">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">2
                                </EnumerationValue>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="IM">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">3
                                </EnumerationValue>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="Both">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">4
                                </EnumerationValue>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="SMSPreferred">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">5
                                </EnumerationValue>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="EmailPreferred">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">6
                                </EnumerationValue>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
            <xsd:element name="TransportType" nillable="true" type="tns:TransportType"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified"
                    targetNamespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06"
                    xmlns:tns="http://schemas.altinn.no/services/ServiceEngine/Notification/2015/06">
            <xsd:import namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10"/>
            <xsd:complexType name="SendNotificationResultList">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents the result of a SendStandaloneNotificationV3 service call.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="NotificationResult" nillable="true"
                                 type="tns:NotificationResult"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="SendNotificationResultList" nillable="true" type="tns:SendNotificationResultList"/>
            <xsd:complexType name="NotificationResult">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                A collection of SendStandaloneNotificationReceiverEndpointResults for a Notification.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="EndPoints" nillable="true" type="tns:EndPointResultList">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets list of EndPoints.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="NotificationType" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets Notification Type.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReporteeNumber" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets Reportee.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="NotificationResult" nillable="true" type="tns:NotificationResult"/>
            <xsd:complexType name="EndPointResultList">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                A collection of ReceiverEndPointResults.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" name="EndPointResult" nillable="true"
                                 type="tns:EndPointResult"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="EndPointResultList" nillable="true" type="tns:EndPointResultList"/>
            <xsd:complexType name="EndPointResult">
                <xsd:annotation>
                    <xsd:appinfo>
                        <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                   xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                   xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                   xmlns:d1p1="XmlCommentsExporter.Annotation">
                            <d1p1:Text z:Id="2">&lt;summary&gt;
                                Represents a ReceiverEndpoint that received a SendStandaloneNotification.
                                &lt;/summary&gt;
                            </d1p1:Text>
                        </Surrogate>
                    </xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="Name" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets name of the Reportee
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ReceiverAddress" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the ReceiverAddress.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="RetrieveFromProfile" nillable="true" type="xsd:boolean">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets a value indicating whether the receiver address was retrieved from
                                        the reportee profile.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="TransportType" type="q9:TransportType"
                                 xmlns:q9="http://schemas.altinn.no/serviceengine/formsengine/2009/10">
                        <xsd:annotation>
                            <xsd:appinfo>
                                <Surrogate z:Id="1" i:type="d1p1:Annotation"
                                           xmlns="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                                           xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"
                                           xmlns:d1p1="XmlCommentsExporter.Annotation">
                                    <d1p1:Text z:Id="2">&lt;summary&gt;
                                        Gets or sets the TransportType.
                                        &lt;/summary&gt;
                                    </d1p1:Text>
                                </Surrogate>
                            </xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="EndPointResult" nillable="true" type="tns:EndPointResult"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="INotificationAgencyExternalBasic_Test_InputMessage">
        <wsdl:part name="parameters" element="q10:Test" xmlns:q10="http://www.altinn.no/services/2009/10"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_Test_OutputMessage">
        <wsdl:part name="parameters" element="q11:TestResponse" xmlns:q11="http://www.altinn.no/services/2009/10"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_Test_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q12:AltinnFault"
                   xmlns:q12="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasic_InputMessage">
        <wsdl:part name="parameters" element="tns:SendStandaloneNotificationBasic"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasic_OutputMessage">
        <wsdl:part name="parameters" element="tns:SendStandaloneNotificationBasicResponse"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasic_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q13:AltinnFault"
                   xmlns:q13="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV2_InputMessage">
        <wsdl:part name="parameters" element="tns:SendStandaloneNotificationBasicV2"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV2_OutputMessage">
        <wsdl:part name="parameters" element="tns:SendStandaloneNotificationBasicV2Response"/>
    </wsdl:message>
    <wsdl:message
            name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV2_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q14:AltinnFault"
                   xmlns:q14="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV3_InputMessage">
        <wsdl:part name="parameters" element="tns:SendStandaloneNotificationBasicV3"/>
    </wsdl:message>
    <wsdl:message name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV3_OutputMessage">
        <wsdl:part name="parameters" element="tns:SendStandaloneNotificationBasicV3Response"/>
    </wsdl:message>
    <wsdl:message
            name="INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV3_AltinnFaultFault_FaultMessage">
        <wsdl:part name="detail" element="q15:AltinnFault"
                   xmlns:q15="http://www.altinn.no/services/common/fault/2009/10"/>
    </wsdl:message>
    <wsdl:portType name="INotificationAgencyExternalBasic">
        <wsdl:documentation>&lt;summary&gt;&#xD;
            External interface for exposing service operations used by AgencySystem for sending&#xD;
            standalone notifications to users&#xD;
            &lt;/summary&gt;
        </wsdl:documentation>
        <wsdl:operation name="Test">
            <wsdl:input wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test"
                        message="tns:INotificationAgencyExternalBasic_Test_InputMessage"/>
            <wsdl:output wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse"
                         message="tns:INotificationAgencyExternalBasic_Test_OutputMessage"/>
            <wsdl:fault wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault"
                        name="AltinnFaultFault"
                        message="tns:INotificationAgencyExternalBasic_Test_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="SendStandaloneNotificationBasic">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                SendStandaloneNotification operation lets the agency send notifications to users based on templates&#xD;
                &lt;/summary&gt;&#xD;
                &lt;param name="systemUserName"&gt;&#xD;
                System user name is the relevant agency system name that is registered in Altinn - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                System password is the password for the corresponding registered agency system - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="standaloneNotifications"&gt;&#xD;
                Contains a list of standalone notification BE with details for the notifications that is to be sent:&#xD;
                ReporteeNumber: The SSN of the receiver of the notification (can be used for lookup in user profile if
                ReceiverEndPoints.ReceiverAddress is not set -&#xD;
                mandatory parameter,&#xD;
                ReceiverEndPoints: List of mandatory TransportType(SMS, Email or Both) and ReceiverAddress
                (optionally-if not set profile information will be used)&#xD;
                for the recipient - mandatory parameter,&#xD;
                LanguageID: Localization language for the notification (English 1033, Bokmål 1044, Nynorsk 2068) -
                mandatory parameter,&#xD;
                NotificationType: identifies the notification template to be used (template needs to be available in
                database) - mandatory parameter,&#xD;
                TextTokens: TokenNumber and TokenValue pairs of numbers and the corresponding substitution string -
                provide if template support this feature,&#xD;
                FromAddress: Optional parameter that can be used to set the from field for e-mail notifications, if not
                set default Altinn address will be used,&#xD;
                ShipmentDateTime: Optional parameter if the notification is to be sent at a later time&#xD;
                &lt;/param&gt;
            </wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasic"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasic_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicResponse"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasic_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicAltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasic_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="SendStandaloneNotificationBasicV2">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                SendStandaloneNotification operation lets the agency send notifications to users based on templates&#xD;
                &lt;/summary&gt;&#xD;
                &lt;param name="systemUserName"&gt;&#xD;
                System user name is the relevant agency system name that is registered in Altinn - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                System password is the password for the corresponding registered agency system - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="standaloneNotifications"&gt;&#xD;
                Contains a list of standalone notification BE with details for the notifications that is to be sent:&#xD;
                ReporteeNumber: The SSN of the receiver of the notification (can be used for lookup in user profile if
                ReceiverEndPoints.ReceiverAddress is not set -&#xD;
                mandatory parameter,&#xD;
                ReceiverEndPoints: List of mandatory TransportType(SMS, Email or Both) and ReceiverAddress
                (optionally-if not set profile information will be used)&#xD;
                for the recipient - mandatory parameter,&#xD;
                LanguageID: Localization language for the notification (English 1033, Bokmål 1044, Nynorsk 2068) -
                mandatory parameter,&#xD;
                NotificationType: identifies the notification template to be used (template needs to be available in
                database) - mandatory parameter,&#xD;
                TextTokens: TokenNumber and TokenValue pairs of numbers and the corresponding substitution string -
                provide if template support this feature,&#xD;
                FromAddress: Optional parameter that can be used to set the from field for e-mail notifications, if not
                set default Altinn address will be used,&#xD;
                ShipmentDateTime: Optional parameter if the notification is to be sent at a later time&#xD;
                &lt;/param&gt;&#xD;
                &lt;returns&gt;&#xD;
                Returns a success or failure message&#xD;
                &lt;/returns&gt;
            </wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV2"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV2_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV2Response"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV2_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV2AltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV2_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="SendStandaloneNotificationBasicV3">
            <wsdl:documentation>&lt;summary&gt;&#xD;
                SendStandaloneNotification operation lets the agency send notifications to users based on templates.&#xD;
                When Reportee is an Organization and ReceiverEndpoint has no ReceiverAddress, receiverAddresses will be
                &#xD;
                generated from the Organization Profile, and additional ReceiverEndPoints will be generated based on the
                &#xD;
                UnitReportee profile and supplied ServiceCode.&#xD;
                &lt;/summary&gt;&#xD;
                &lt;param name="systemUserName"&gt;&#xD;
                System user name is the relevant agency system name that is registered in Altinn - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="systemPassword"&gt;&#xD;
                System password is the password for the corresponding registered agency system - mandatory parameter&#xD;
                &lt;/param&gt;&#xD;
                &lt;param name="standaloneNotifications"&gt;&#xD;
                Contains a list of standalone notification BE with details for the notifications that is to be sent:&#xD;
                ReporteeNumber: The SSN of the receiver of the notification (can be used for lookup in user profile if
                ReceiverEndPoints.ReceiverAddress is not set -&#xD;
                mandatory parameter,&#xD;
                ReceiverEndPoints: List of mandatory TransportType(SMS, Email or Both) and ReceiverAddress
                (optionally-if not set profile information will be used)&#xD;
                for the recipient - mandatory parameter,&#xD;
                LanguageID: Localization language for the notification (English 1033, Bokmål 1044, Nynorsk 2068) -
                mandatory parameter,&#xD;
                NotificationType: identifies the notification template to be used (template needs to be available in
                database) - mandatory parameter,&#xD;
                TextTokens: TokenNumber and TokenValue pairs of numbers and the corresponding substitution string -
                provide if template support this feature,&#xD;
                FromAddress: Optional parameter that can be used to set the from field for e-mail notifications, if not
                set default Altinn address will be used,&#xD;
                ShipmentDateTime: Optional parameter if the notification is to be sent at a later time&#xD;
                &lt;/param&gt;&#xD;
                &lt;returns&gt;&#xD;
                Returns a success or failure message&#xD;
                &lt;/returns&gt;
            </wsdl:documentation>
            <wsdl:input
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV3"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV3_InputMessage"/>
            <wsdl:output
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV3Response"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV3_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV3AltinnFaultFault"
                    name="AltinnFaultFault"
                    message="tns:INotificationAgencyExternalBasic_SendStandaloneNotificationBasicV3_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_INotificationAgencyExternalBasic" type="tns:INotificationAgencyExternalBasic">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Test">
            <soap:operation soapAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test"
                            style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="SendStandaloneNotificationBasic">
            <soap:operation
                    soapAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasic"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="SendStandaloneNotificationBasicV2">
            <soap:operation
                    soapAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV2"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="SendStandaloneNotificationBasicV3">
            <soap:operation
                    soapAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV3"
                    style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap:fault name="AltinnFaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="NotificationAgencyExternalBasicSF">
        <wsdl:port name="BasicHttpBinding_INotificationAgencyExternalBasic"
                   binding="tns:BasicHttpBinding_INotificationAgencyExternalBasic">
            <soap:address location="http://tt02.altinn.no/ServiceEngineExternal/NotificationAgencyExternalBasic.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>