<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GOSYSSakWSEXP_GOSYSSakHttp_Service" targetNamespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/Sak/Binding" xmlns:Port_0="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/Sak" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/Sak/Binding">
  <wsdl:import namespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/Sak" location="no/nav/inf/GOSYSSak.wsdl">
    </wsdl:import>
  <wsdl:binding name="GOSYSSakWSEXP_GOSYSSakHttpBinding" type="Port_0:GOSYSSak">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentSakListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentSakListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentSakListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opprettSakBolk">
      <soap:operation soapAction=""/>
      <wsdl:input name="opprettSakBolkRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opprettSakBolkResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="lagreSakBolk">
      <soap:operation soapAction=""/>
      <wsdl:input name="lagreSakBolkRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="lagreSakBolkResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opprettEllerHentSakBolk">
      <soap:operation soapAction=""/>
      <wsdl:input name="opprettEllerHentSakBolkRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opprettEllerHentSakBolkResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GOSYSSakWSEXP_GOSYSSakHttpService">
    <wsdl:port name="GOSYSSakWSEXP_GOSYSSakHttpPort" binding="this:GOSYSSakWSEXP_GOSYSSakHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-sak-gosys-3.0.0Web/sca/GOSYSSakWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
