<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GOSYSInfotrygdVedtakWSEXP_GOSYSInfotrygdVedtakHttp_Service" targetNamespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdVedtak/Binding" xmlns:Port_0="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdVedtak" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdVedtak/Binding">
  <wsdl:import namespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/InfotrygdVedtak" location="no/nav/inf/GOSYSInfotrygdVedtak.wsdl">
    </wsdl:import>
  <wsdl:binding name="GOSYSInfotrygdVedtakWSEXP_GOSYSInfotrygdVedtakHttpBinding" type="Port_0:GOSYSInfotrygdVedtak">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentVedtakListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentVedtakListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentVedtakListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGosysGenerisk">
        <soap:fault name="faultGosysGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GOSYSInfotrygdVedtakWSEXP_GOSYSInfotrygdVedtakHttpService">
    <wsdl:port name="GOSYSInfotrygdVedtakWSEXP_GOSYSInfotrygdVedtakHttpPort" binding="this:GOSYSInfotrygdVedtakWSEXP_GOSYSInfotrygdVedtakHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-sak-gosys-3.0.0Web/sca/GOSYSInfotrygdVedtakWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
