<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GOSYSNAVAnsattWSEXP_GOSYSNAVansattHttp_Service" targetNamespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/NAVansatt/Binding" xmlns:Port_0="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/NAVansatt" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/NAVansatt/Binding">
  <wsdl:import namespace="http://nav-cons-sak-gosys-3.0.0/no/nav/inf/NAVansatt" location="no/nav/inf/GOSYSNAVansatt.wsdl">
    </wsdl:import>
  <wsdl:binding name="GOSYSNAVAnsattWSEXP_GOSYSNAVansattHttpBinding" type="Port_0:GOSYSNAVansatt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentNAVAnsatt">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentNAVAnsattRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentNAVAnsattResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSNAVAnsattIkkeFunnet">
        <soap:fault name="faultGOSYSNAVAnsattIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentNAVAnsattEnhetListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentNAVAnsattEnhetListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentNAVAnsattEnhetListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSNAVAnsattIkkeFunnet">
        <soap:fault name="faultGOSYSNAVAnsattIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentNAVAnsattFagomradeListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentNAVAnsattFagomradeListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentNAVAnsattFagomradeListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSNAVAnsattIkkeFunnet">
        <soap:fault name="faultGOSYSNAVAnsattIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentNAVAnsattListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentNAVAnsattListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentNAVAnsattListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGOSYSNAVEnhetIkkeFunnet">
        <soap:fault name="faultGOSYSNAVEnhetIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="finnArenaNAVAnsattListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="finnArenaNAVAnsattListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="finnArenaNAVAnsattListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGOSYSGenerisk">
        <soap:fault name="faultGOSYSGenerisk" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGOSYSNAVEnhetIkkeFunnet">
        <soap:fault name="faultGOSYSNAVEnhetIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GOSYSNAVAnsattWSEXP_GOSYSNAVansattHttpService">
    <wsdl:port name="GOSYSNAVAnsattWSEXP_GOSYSNAVansattHttpPort" binding="this:GOSYSNAVAnsattWSEXP_GOSYSNAVansattHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-sak-gosys-3.0.0Web/sca/GOSYSNAVAnsattWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
