<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/Binding" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/Binding" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="arbeidsfordeling.wsdl" namespace="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/"/>
  <wsdl:binding name="Arbeidsfordeling_v1Binding" type="wsdl_1:Arbeidsfordeling_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="finnBehandlendeEnhetListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/BindingfinnBehandlendeEnhetListe/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="finnBehandlendeEnhetListeFault">
        <soap:fault name="finnBehandlendeEnhetListeFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/Bindingping/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="finnAlleBehandlendeEnheterListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/BindingfinnAlleBehandlendeEnheterListe/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="finnAlleBehandlendeEnheterListeFault">
        <soap:fault name="finnAlleBehandlendeEnheterListeFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Arbeidsfordeling_v1">
    <wsdl:port binding="tns:Arbeidsfordeling_v1Binding" name="Arbeidsfordeling_v1Port">
      <soap:address location="http://nav.no/tjeneste/virksomhet/arbeidsfordeling/v1/BindingArbeidsfordeling_v1/Arbeidsfordeling_v1Port"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>