<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/oppfoelging/v1/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/virksomhet/oppfoelging/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/oppfoelging/v1/" location="Oppfoelging.wsdl">
    </wsdl:import>
  <wsdl:binding name="OppfoelgingPortTypeBinding" type="tns:OppfoelgingPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="hentOppfoelgingskontraktListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/oppfoelging/v1/OppfoelgingPortType/hentOppfoelgingskontraktListeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/oppfoelging/v1/OppfoelgingPortType/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="hentOppfoelgingsstatus">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/oppfoelging/v1/OppfoelgingPortType/hentOppfoelgingsstatusRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="personIkkeFunnet">
        <soap:fault name="personIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Oppfoelging_v1">
    <wsdl:port name="OppfoelgingPortTypePort" binding="tns:OppfoelgingPortTypeBinding">
      <soap:address location="http://localhost:9080/arena-ws/services/oppfoelging"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
