<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/" location="arbeidOgAktivitetVedtak.wsdl">
    </wsdl:import>
  <wsdl:binding name="arbeidOgAktivitetVedtak_v1Binding" type="wsdl_1:arbeidOgAktivitetVedtak_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="hentVedtak">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/arbeidOgAktivitetVedtak_v1/hentVedtakRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="vedtakIkkeFunnet">
        <soap:fault name="vedtakIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/arbeidOgAktivitetVedtak_v1/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="finnVedtakListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/arbeidOgAktivitetVedtak/v1/arbeidOgAktivitetVedtak_v1/finnVedtakListeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ArbeidOgAktivitetVedtak_v1">
    <wsdl:port name="arbeidOgAktivitetVedtak_v1Port" binding="tns:arbeidOgAktivitetVedtak_v1Binding">
      <soap:address location="http://localhost:9080/virksomhet/arbeidOgAktivitetVedtak_v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
