<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="Binding" targetNamespace="http://no.nav/virksomhet/tjenester/arbeidsgiver/v2/Binding/" xmlns:arbeidsgiver="http://nav.no/virksomhet/tjenester/arbeidsgiver/v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://no.nav/virksomhet/tjenester/arbeidsgiver/v2/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="../arbeidsgiver.wsdl" namespace="http://nav.no/virksomhet/tjenester/arbeidsgiver/v2"/>
  <wsdl:binding name="ArbeidsgiverBinding" type="arbeidsgiver:Arbeidsgiver">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="finnOrganisasjonsListe">
      <soap:operation soapAction="http://no.nav/virksomhet/tjenester/arbeidsgiver/v2/Binding/finnOrganisasjonsListe/"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="finnOrganisasjonsListe">
      <wsdl:input/>
      <wsdl:output/>
    </wsdl:operation>
    <wsdl:operation name="hentKontonummerhistorikk">
      <soap:operation soapAction="http://no.nav/virksomhet/tjenester/arbeidsgiver/v2/Binding/hentKontonummerhistorikk/"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="hentKontonummerhistorikkFault">
        <soap:fault name="hentKontonummerhistorikkFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentKontonummerhistorikk">
      <wsdl:input/>
      <wsdl:output/>
      <wsdl:fault name="hentKontonummerhistorikkFault"/>
    </wsdl:operation>
    <wsdl:operation name="hentOrganisasjon">
      <soap:operation soapAction="http://no.nav/virksomhet/tjenester/arbeidsgiver/v2/Binding/hentOrganisasjon/"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="hentOrganisasjonFault">
        <soap:fault name="hentOrganisasjonFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentOrganisasjon">
      <wsdl:input/>
      <wsdl:output/>
      <wsdl:fault name="hentOrganisasjonFault"/>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Arbeidsgiver">
    <wsdl:port binding="tns:ArbeidsgiverBinding" name="ArbeidsgiverPort">
      <soap:address location="http://no.nav/virksomhet/tjenester/arbeidsgiver/v2/Binding/Arbeidsgiver/ArbeidsgiverPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>