<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1" location="behandleAktivitetsplan.wsdl">
    </wsdl:import>
  <wsdl:binding name="BehandleAktivitetsplan_v1Binding" type="wsdl_1:BehandleAktivitetsplan_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="OpprettNyEgenAktivitet">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1/BehandleAktivitetsplan_v1/OpprettNyEgenAktivitetRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="OpprettNyStillingAktivitet">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1/BehandleAktivitetsplan_v1/OpprettNyStillingAktivitetRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensing">
        <soap:fault name="sikkerhetsbegrensing" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1/BehandleAktivitetsplan_v1/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="HentAktivitetsplan">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/brukerdialog/behandleAktivitetsplan/v1/BehandleAktivitetsplan_v1/HentAktivitetsplanRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensing">
        <soap:fault name="sikkerhetsbegrensing" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BehandleAktivitetsplan_v1">
    <wsdl:port name="BehandleAktivitetsplan_v1Port" binding="tns:BehandleAktivitetsplan_v1Binding">
      <soap:address location="http://localhost:9080/domene/brukerdialog/aktivitetsplan_v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
