<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Binding/" xmlns:journal="http://nav.no/virksomhet/tjenester/arkiv/journal/v2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Binding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/arkiv/journal/v2" location="../journal.wsdl">
    </wsdl:import>
  <wsdl:binding name="JournalBinding" type="journal:Journal">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="finnJournalpost">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Journal/finnJournalpostRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="hentDokumentURL">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Journal/hentDokumentURLRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="filUuidFinnesIkke">
        <soap:fault name="filUuidFinnesIkke" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="journalpostIkkeFunnet">
        <soap:fault name="journalpostIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentDokument">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Journal/hentDokumentRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="filUuidFinnesIkke">
        <soap:fault name="filUuidFinnesIkke" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="journalpostIkkeFunnet">
        <soap:fault name="journalpostIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentJournalpost">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Journal/hentJournalpostRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="journalpostIkkeFunnet">
        <soap:fault name="journalpostIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="identifiserBrevgruppe">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/arkiv/journal/v2/Journal/identifiserBrevgruppeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Journal">
    <wsdl:port name="JournalPort" binding="tns:JournalBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-journal_v2Web/sca/JournalWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
