<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/samhandler/v2/Binding/" xmlns:samhandler="http://nav.no/virksomhet/tjenester/samhandler/v2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://nav.no/virksomhet/tjenester/samhandler/v2/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import namespace="http://nav.no/virksomhet/tjenester/samhandler/v2" location="samhandler.wsdl"/>
    <wsdl:binding name="SamhandlerBinding" type="samhandler:Samhandler">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsaw:UsingAddressing/>
        <wsdl:operation name="hentAutorisasjonOgRettighetListe">
            <soap:operation soapAction=""/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="hentSamhandlerNavn">
            <soap:operation soapAction=""/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="samhandlerIkkeFunnet">
                <soap:fault name="samhandlerIkkeFunnet" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="hentSamhandlerPrioritertAdresse">
            <soap:operation soapAction=""/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="samhandlerIkkeFunnet">
                <soap:fault name="samhandlerIkkeFunnet" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="Samhandler">
        <wsdl:port name="SamhandlerPort" binding="tns:SamhandlerBinding">
            <soap:address location="http://localhost:9080/nav-tjeneste-samhandler_v2Web/sca/SamhandlerWSEXP"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
