<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/journal/v3/Binding" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://nav.no/tjeneste/virksomhet/journal/v3/Binding" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/journal/v3" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="journal.wsdl" namespace="http://nav.no/tjeneste/virksomhet/journal/v3"/>
  <wsdl:binding name="Journal_v3Binding" type="wsdl_1:Journal_v3">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/journal/v3/Journal_v3/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="hentDokument">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/journal/v3/Journal_v3/hentDokumentRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="hentDokumentFault">
        <soap:fault name="hentDokumentFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="hentDokumentFault1">
        <soap:fault name="hentDokumentFault1" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="hentDokumentFault2">
        <soap:fault name="hentDokumentFault2" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentDokumentURL">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/journal/v3/Journal_v3/hentDokumentURLRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="dokumentIkkeFunnet">
        <soap:fault name="dokumentIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentKjerneJournalpostListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/journal/v3/Journal_v3/hentKjerneJournalpostListeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Journal_v3">
    <wsdl:port binding="tns:Journal_v3Binding" name="Journal_v3Port">
      <soap:address location="http://nav.no/tjeneste/virksomhet/journal/v3/Journal_v3/Journal_v3Port"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>