<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/behandleInntekt/v1/Binding/" xmlns:behandleinntekt="http://nav.no/tjeneste/virksomhet/behandleinntekt/v1" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://nav.no/tjeneste/virksomhet/behandleInntekt/v1/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/behandleinntekt/v1" location="behandleInntekt.wsdl">
    </wsdl:import>
  <wsdl:binding name="BehandleInntekt_v1Binding" type="behandleinntekt:BehandleInntekt_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="lagreForventetInntekt">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleinntekt/v1/BehandleInntekt_v1/lagreForventetInntektRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="personIkkeFunnet">
        <soap:fault name="personIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsBegrensning">
        <soap:fault name="sikkerhetsBegrensning" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleinntekt/v1/BehandleInntekt_v1/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="lagreForventetInntektListeBolk">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/behandleinntekt/v1/BehandleInntekt_v1/lagreForventetInntektListeBolkRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BehandleInntekt">
    <wsdl:port name="BehandleInntekt_v1Port" binding="tns:BehandleInntekt_v1Binding">
      <soap:address location="http://localhost:9080/virksomhet/BehandleInntekt_v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
