<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:vedlikeholdInntektsabonnement="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1/Binding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1" location="../vedlikeholdInntektsabonnement.wsdl">
    </wsdl:import>
  <wsdl:binding name="VedlikeholdInntektsabonnement_v1Binding" type="vedlikeholdInntektsabonnement:VedlikeholdInntektsabonnement_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="opprettAbonnement">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1/VedlikeholdInntektsabonnement_v1/opprettAbonnementRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsbegrensninger">
        <soap:fault name="sikkerhetsbegrensninger" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="personIkkeFunnet">
        <soap:fault name="personIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opphoerAbonnement">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1/VedlikeholdInntektsabonnement_v1/opphoerAbonnementRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ugyldigInput">
        <soap:fault name="ugyldigInput" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="sikkerhetsbegrensning">
        <soap:fault name="sikkerhetsbegrensning" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/vedlikeholdInntektsabonnement/v1/VedlikeholdInntektsabonnement_v1/pingRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="VedlikeholdInntektsabonnement">
    <wsdl:port name="VedlikeholdInntektsabonnement_v1Port" binding="tns:VedlikeholdInntektsabonnement_v1Binding">
      <soap:address location="http://localhost:9080/virksomhet/vedlikeholdInntektsabonnement_v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
