<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PersonsokWSEXP_PersonsokHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/person/personsok/v1/Binding" xmlns:Port_0="http://nav.no/virksomhet/tjenester/person/personsok/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/person/personsok/v1/Binding">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/person/personsok/v1" location="no/nav/virksomhet/tjenester/person/personsok/personsok.wsdl">
    </wsdl:import>
  <wsdl:binding name="PersonsokWSEXP_PersonsokHttpBinding" type="Port_0:Personsok">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sokNavn">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="forMangeForekomster">
        <soap:fault name="forMangeForekomster" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigKombinasjon">
        <soap:fault name="ugyldigKombinasjon" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="sokAdresse">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="forMangeForekomster">
        <soap:fault name="forMangeForekomster" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigKombinasjon">
        <soap:fault name="ugyldigKombinasjon" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="sokKombinasjon">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="forMangeForekomster">
        <soap:fault name="forMangeForekomster" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ugyldigKombinasjon">
        <soap:fault name="ugyldigKombinasjon" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PersonsokWSEXP_PersonsokHttpService">
    <wsdl:port name="PersonsokWSEXP_PersonsokHttpPort" binding="this:PersonsokWSEXP_PersonsokHttpBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-personsok_v1Web/sca/PersonsokWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
