<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1" location="sakOgBehandling.wsdl">
    </wsdl:import>
  <wsdl:binding name="SakOgBehandling_v1Binding" type="wsdl_1:SakOgBehandling_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="finnSakOgBehandlingskjedeListe">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1/SakOgBehandling_v1/finnSakOgBehandlingskjedeListeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="hentBehandling">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1/SakOgBehandling_v1/hentBehandlingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="behandlingIkkeFunnet">
        <soap:fault name="behandlingIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentBehandlingskjedensBehandlinger">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1/SakOgBehandling_v1/hentBehandlingskjedensBehandlingerRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="behandlingskjedeIkkeFunnet">
        <soap:fault name="behandlingskjedeIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/virksomhet/sakOgBehandling/v1/SakOgBehandling_v1/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SakOgBehandling_v1">
    <wsdl:port name="SakOgBehandling_v1Port" binding="tns:SakOgBehandling_v1Binding">
      <soap:address location="http://localhost:9080/virksomhet/SakOgBehandling_v1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
