<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/ruting/Binding/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://nav.no/virksomhet/tjenester/ruting/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ruting="http://nav.no/virksomhet/tjenester/ruting/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/ruting/v1" location="../ruting.wsdl">
    </wsdl:import>
  <wsdl:binding name="RutingBinding" type="ruting:Ruting">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="finnAnsvarligEnhetForSak">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/ruting/v1/Ruting/finnAnsvarligEnhetForSakRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="finnAnsvarligEnhetForOppgavetype">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/ruting/v1/Ruting/finnAnsvarligEnhetForOppgavetypeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Ruting">
    <wsdl:port name="RutingPort" binding="tns:RutingBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-ruting_v1Web/sca/rutingWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
