<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/avstemming/v1/Binding" xmlns:avstemming="http://nav.no/virksomhet/tjenester/avstemming/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://nav.no/virksomhet/tjenester/avstemming/v1/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="../avstemming.wsdl" namespace="http://nav.no/virksomhet/tjenester/avstemming/v1"/>
  <wsdl:binding name="AvstemmingBinding" type="avstemming:Avstemming">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendAsynkronAvstemmingsdata">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/avstemming/v1/BindingsendAsynkronAvstemmingsdata/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="sendAsynkronKonsistensavstemmingsdata">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/avstemming/v1/BindingsendAsynkronKonsistensavstemmingsdata/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Avstemming">
    <wsdl:port binding="tns:AvstemmingBinding" name="AvstemmingPort">
      <soap:address location="http://nav.no/virksomhet/tjenester/avstemming/v1/BindingAvstemming/AvstemmingPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>