<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://nav.no/tjeneste/virksomhet/dokumentinnsendingsoknad/v1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  name="SoknadService"
                  targetNamespace="http://nav.no/tjeneste/virksomhet/dokumentinnsendingsoknad/v1">
    <wsdl:types>

        <xs:schema xmlns:tns="http://nav.no/tjeneste/virksomhet/dokumentinnsendingsoknad/v1"
                   elementFormDefault="unqualified"
                   targetNamespace="http://nav.no/tjeneste/virksomhet/dokumentinnsendingsoknad/v1"
                   xmlns:soknad="http://nav.no/tjeneste/virksomhet/dokumentinnsending/v1/soknad">

            <xs:import namespace="http://nav.no/tjeneste/virksomhet/dokumentinnsending/v1/soknad"
                       schemaLocation="no/nav/tjeneste/virksomhet/dokumentinnsending/v1/soknad/soknad.xsd"/>

            <xs:element name="opprettSoknad" type="soknad:opprettSoknad"/>
            <xs:element name="opprettSoknadResponse" type="soknad:opprettSoknadResponse"/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="opprettSoknadResponse">
        <wsdl:part element="tns:opprettSoknadResponse" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="opprettSoknad">
        <wsdl:part element="tns:opprettSoknad" name="parameters"/>
    </wsdl:message>

    <wsdl:portType name="SoknadPortType">
        <wsdl:operation name="opprettSoknad">
            <wsdl:input message="tns:opprettSoknad" name="opprettSoknad"/>
            <wsdl:output message="tns:opprettSoknadResponse" name="opprettSoknadResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="SoknadBinding" type="tns:SoknadPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="opprettSoknad">
            <soap:operation soapAction="opprettSoknad" style="document"/>
            <wsdl:input name="opprettSoknad">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="opprettSoknadResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="SoknadService">
        <wsdl:port binding="tns:SoknadBinding" name="SoknadPort">
            <soap:address location="http://localhost:8081/virksomhet/Dokumentinnsending_v1"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>